### ISSUE TITLE
Allow for multiple models

### ISSUE THREAD

**Issue by nstogner** [substratusai/helm#1]
Example `values.yaml`:

```yaml
models:
   llama-7b: # The "model" that is referenced in the OpenAI-like API
     enabled: true
     source:
        huggingface: meta-llama/Llama-2-7b
        # gcs: ... # future
    resources:
      nvidia.com/gpu: 2
   opt-350m:
     enabled: true
     source:
        huggingface: facebook/opt-350m
```

**Comment by samos123** [comment]
to summarize, I prefer single model per helm chart for the `text-generation-inference` chart:
* Reduces complexity in helm-chart
* People can create multiple releases of same helm char
* Stay as close as possible to k8s and allow maximum flexibility to tweak and override values

That being said,  I think this could be expressed in another layer or a separate chart.

For inferencing this would be desired UX:
```
name: mistral-7b-vllm
serving: vllm
model:
  source:
    huggingface:
      id: hf-org/mistral-7b

# future maybe never
model:
  source:
    gcs:
      bucket: sam
      path: mistral-7b

resources:
  # optional for CPU only serving e.g. llama.cpp
  accelerators:
    name: nvidia-v100
    count: 1

# replicas: 1 # just use min max
autoscaling:
  min: 1 # default is 0
  max: 1 # default is 3
  concurrentRequests: 4 # default is 1
```
